{
  "train-data-paths": [
    # Red pajama dataset - 1.2 T tokens, nope: 147 Billion
    "/p/fastdata/mmlaion/hummingbird/red_pajama_data/arxiv/arxiv_tokenized_text_document",
    # "./data/enwik8/enwik8_text_document",
    # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/book/book_tokenized_text_document",
    # #"/p/fastdata/mmlaion/hummingbird/red_pajama_data/c4/processed_en/c4_tokenized_text_document",
    # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/wikipedia/wiki_full_tokenized_text_document",
    # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/github/tokenized_text_document",
    # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/stackexchange/tokenized_text_document",
    # # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/cc_classifier_filtered/2019-30/tokenized_text_document",
    # # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/cc_classifier_filtered/2020-05/tokenized_text_document",
    # # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/cc_classifier_filtered/2021-04/tokenized_text_document",
    # # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/cc_classifier_filtered/2022-05/tokenized_text_document",
    # # "/p/fastdata/mmlaion/hummingbird/red_pajama_data/cc_classifier_filtered/2023-06/tokenized_text_document",
    
    # # Conceptual Captions ~ 368 Million tokens
    # "/p/fastdata/mmlaion/hummingbird/cc12m/tokenized_text_document/tokenized_text_document",

    # # MMC4 ~ 234142167944 tokens ~ 234 Billion
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_1_1000_text_document/tokenized_mmc4_1_1000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_1001_2000_text_document/tokenized_mmc4_1001_2000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_2001_3000_text_document/tokenized_mmc4_2001_3000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_3001_4000_text_document/tokenized_mmc4_3001_4000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_4001_5000_text_document/tokenized_mmc4_4001_5000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_5001_6000_text_document/tokenized_mmc4_5001_6000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_6001_7000_text_document/tokenized_mmc4_6001_7000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_7001_8000_text_document/tokenized_mmc4_7001_8000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_8001_9000_text_document/tokenized_mmc4_8001_9000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_9001_10000_text_document/tokenized_mmc4_9001_10000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_10001_11000_text_document/tokenized_mmc4_10001_11000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_11001_12000_text_document/tokenized_mmc4_11001_12000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_12001_13000_text_document/tokenized_mmc4_12001_13000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_13001_14000_text_document/tokenized_mmc4_13001_14000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_14001_15000_text_document/tokenized_mmc4_14001_15000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_15001_16000_text_document/tokenized_mmc4_15001_16000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_16001_17000_text_document/tokenized_mmc4_16001_17000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_17001_18000_text_document/tokenized_mmc4_17001_18000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_18001_19000_text_document/tokenized_mmc4_18001_19000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_19001_20000_text_document/tokenized_mmc4_19001_20000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_20001_21000_text_document/tokenized_mmc4_20001_21000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_21001_22000_text_document/tokenized_mmc4_21001_22000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_22001_23000_text_document/tokenized_mmc4_22001_23000_text_document",
    # "/p/fastdata/mmlaion/hummingbird/mmc4/docs/tokenized_mmc4_23001_23085_text_document/tokenized_mmc4_23001_23085_text_document",
    
    # # LAION 1B ~ 26.5 billion
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_0_75_text_document/tokenized_mmc4_0_75_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_76_150_text_document/tokenized_mmc4_76_150_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_151_225_text_document/tokenized_mmc4_151_225_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_226_300_text_document/tokenized_mmc4_226_300_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_301_375_text_document/tokenized_mmc4_301_375_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_376_500_text_document/tokenized_mmc4_376_500_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_501_700_text_document/tokenized_mmc4_501_700_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_701_900_text_document/tokenized_mmc4_701_900_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_901_1100_text_document/tokenized_mmc4_901_1100_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion1b-nolang/tokenized_mmc4_1101_1136_text_document/tokenized_mmc4_1101_1136_text_document",

    # # LAION 2B ~ 54.5 billion
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_0_75_text_document/tokenized_mmc4_0_75_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_76_150_text_document/tokenized_mmc4_76_150_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_151_225_text_document/tokenized_mmc4_151_225_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_226_300_text_document/tokenized_mmc4_226_300_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_301_375_text_document/tokenized_mmc4_301_375_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_376_500_text_document/tokenized_mmc4_376_500_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_501_700_text_document/tokenized_mmc4_501_700_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_701_900_text_document/tokenized_mmc4_701_900_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_901_1100_text_document/tokenized_mmc4_901_1100_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_1101_1300_text_document/tokenized_mmc4_1101_1300_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_1301_1500_text_document/tokenized_mmc4_1301_1500_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_1501_1700_text_document/tokenized_mmc4_1501_1700_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_1701_1900_text_document/tokenized_mmc4_1701_1900_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_1901_2100_text_document/tokenized_mmc4_1901_2100_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-en/tokenized_mmc4_2101_2220_text_document/tokenized_mmc4_2101_2220_text_document",

    # # LAION 2B MULTI ~ 64.5 billion
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1_75_text_document/tokenized_mmc4_1_75_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_76_150_text_document/tokenized_mmc4_76_150_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_226_300_text_document/tokenized_mmc4_226_300_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_301_375_text_document/tokenized_mmc4_301_375_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_376_500_text_document/tokenized_mmc4_376_500_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_501_700_text_document/tokenized_mmc4_501_700_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_701_900_text_document/tokenized_mmc4_701_900_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_901_1100_text_document/tokenized_mmc4_901_1100_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1101_1300_text_document/tokenized_mmc4_1101_1300_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1301_1500_text_document/tokenized_mmc4_1301_1500_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1501_1700_text_document/tokenized_mmc4_1501_1700_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1701_1900_text_document/tokenized_mmc4_1701_1900_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_1901_2100_text_document/tokenized_mmc4_1901_2100_text_document",
    # "/p/fastdata/mmlaion/hummingbird/laion5b/laion2b-multi/tokenized_mmc4_2101_2163_text_document/tokenized_mmc4_2101_2163_text_document",
  ],
  "test-data-paths": ["/p/fastdata/mmlaion/hummingbird/red_pajama_data/the_pile/test_tokenized_text_document"],
  "valid-data-paths": ["/p/fastdata/mmlaion/hummingbird/red_pajama_data/the_pile/val_tokenized_text_document"],
  "train-data-weights": [
    # 80.38
    5.31,
    # 4.93,
    # # 12.30,
    # 4.55,
    # 11.19,
    # 3.79,
    # # 10.992,
    # # 10.992,
    # # 10.992,
    # # 10.992,
    # # 10.992,

    # # 0.025
    # 0.07,

    # # 9.67
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 1.92,
    # 0.16,


    # # 1.808
    # 0.33,
    # 0.33,
    # 0.33,
    # 0.33,
    # 0.33,
    # 0.55,
    # 0.88,
    # 0.88,
    # 0.88,
    # 0.158,

    # # 3.714
    # 0.35,
    # 0.35,
    # 0.35,
    # 0.35,
    # 0.35,
    # 0.58,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.932,
    # 0.55,

    # # 4.403
    # 0.43,
    # 0.43,
    
    # 0.43,
    # 0.43,
    # 0.73,
    # 1.17,
    # 1.17,
    # 1.17,
    # 1.17,
    # 1.17,
    # 1.17,
    # 1.17,
    # 1.17,
    # 0.36,
  ],
  "test-data-weights": [
    1.
  ],
  "valid-data-weights": [
    1.
  ],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/p/project/ccstdl/gupta6/gpt-neox/data/20B_tokenizer.json",


  "save": "hummingbird_small_final11",
  "load": "hummingbird_small_final11",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard/hummingbird_small_final5",
  "log-dir": "logs/hummingbird_small_final5",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "hummingbird",
  "no_ssh_check": True,
  "num_workers": 5,
}

