# Parameters used for text generation
# Make sure `load` is specified somewhere else
{
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text-gen-type": "input-file",

  # Params for all
  "maximum_tokens": 16,
  "prompt_end": "\n",
  "temperature": 1.0,
  "top_p": 0.0,
  "top_k": 0,
  "recompute": false,

  # `unconditional`: samples
  "num-samples": 1,

  # input/output file
  "sample-input-file": "prompts_for_summit.txt",
  "sample-output-file": "prompts_for_summit_output_lora_edu_05.txt",
}
